name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 8
          distribution: "adopt"
          cache: "gradle"

      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v3.3.2
      #   with:
      #     gradle-version: 6.9.4
      #     add-job-summary: never

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          name: skidbounce
          path: build/libs/skidbounce-v?.?.?.jar
          if-no-files-found: error
